name: get_code_status
description: a dart package that interprets status codes.
version: 1.0.1
homepage: https://github.com/c3k4ah/get_code_status
repository: https://github.com/c3k4ah/get_code_status

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
